version: '3.7'
services:

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/http.conf:/etc/nginx/sites-enabled/http.conf
      - ./nginx/site.conf:/etc/nginx/sites-enabled/site.conf
      - ../../:/src/
    command: 'nginx -g "daemon off;"'
    ports:
      - 80:80

  php:
    build: ./php
    volumes:
      - ../../:/src/
      - ./php/php-cli.ini:/etc/php/7.2/cli/conf.d/php-cli.ini
      - ./php/php-fpm.ini:/etc/php/7.2/fpm/conf.d/php-fpm.ini
      - ./php/pool.conf:/etc/php/7.2/fpm/pool.d/www.conf
    command: 'php-fpm7.2 -F'
    network_mode: "host"

  redis:
    build: ./redis 
    
  db:
    build: ./postgres
    volumes:
      - ./postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ../../:/src/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass